# Generated by Django 5.1.2 on 2024-11-07 21:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('Server', 'Server'), ('Hub', 'Hub'), ('Switch', 'Switch'), ('Router', 'Router'), ('Modem', 'Modem'), ('Media Converters', 'Media Converters'), ('Optical Transceivers', 'Optical Transceivers')], max_length=40)),
                ('mac_address', models.CharField(max_length=12, validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(12)])),
                ('total_ports', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)])),
                ('ports_available', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(64)])),
                ('port_bitmap', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_type', models.CharField(choices=[('CAT5e', 'CAT5e'), ('CAT6', 'CAT6'), ('CAT6a', 'CAT6a'), ('Coaxial', 'Coaxial'), ('Single-Mode FIber Optic', 'Single-Mode FIber Optic'), ('Multi-Mode Fiber Optic', 'Multi-Mode Fiber Optic'), ('OM3/OM4', 'OM3/OM4'), ('OM5', 'OM5'), ('MTP/MPO', 'MTP/MPO')], max_length=100)),
                ('cable_length', models.IntegerField(choices=[(5, '5ft.'), (8, '8ft.'), (12, '12ft.'), (24, '24ft.'), (36, '36ft.'), (48, '48ft.')])),
                ('last_validated', models.DateTimeField(auto_now=True)),
                ('port_1', models.IntegerField(validators=[django.core.validators.MaxValueValidator(64), django.core.validators.MinValueValidator(1)])),
                ('port_2', models.IntegerField(validators=[django.core.validators.MaxValueValidator(64), django.core.validators.MinValueValidator(1)])),
                ('device_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device1', to='network_connections.device')),
                ('device_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device2', to='network_connections.device')),
            ],
        ),
    ]
